networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
    name: v44cccsg04o84s8wo480w04o_prometheus-data
  grafana_data:
    name: v44cccsg04o84s8wo480w04o_grafana-data

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    expose:
      - "9090"
    networks:
      - monitoring
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - "9100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./config/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./config/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus
