global:
  scrape_interval: 15s # How often to scrape targets by default.
  evaluation_interval: 15s # How often to evaluate rules by default.

scrape_configs:
  # Scrape configuration for Prometheus itself.
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 15s
    static_configs:
      - targets: ["cadvisor:8080"]
